[conf]
# options: "cs", "en"
lang = "cs"

[thesis]
authors = [ 
    "Phat Tran Dai",
    # "Jan Novak",
    # "Emil Macha",
]
supervisor = "Borivoj Gulas"
publish-location = "Ostrava"
publish-year = "2025"
type = "bachelor"
assigned = true
assignment = "./assets/thesis-assignment.pdf"

[lang.en] 

title = "Component of Learning Server for Theoretical Computer Science - NP-complete problems 2"
and = "&"
bachelor-thesis = "Bachelor Thesis"
master-thesis = "Diploma Thesis"
phd-thesis = "PhD Thesis"
supervisor = "Supervisor"
section-suplement = "Chapter"
bibliography = "Bibliography"
conclusion = "Conclusion"
abstract = "Abstract"
keywords = "Keywords"
list-of-symbols = "List of symbols and abbreviations"
outline = "Outline"
acknowledgements = "Acknowledgements"
intro = "Intro"

[lang.cs] 
title = "Komponenta výukového serveru TI - P-úplné problémy 2"
and = "&"
bachelor-thesis = "Bakalářská práce"
master-thesis = "Diplomová práce"
phd-thesis = "Disertační práce"
supervisor = "Vedoucí práce"
section-suplement = "Kapitola"
bibliography = "Literatura"
conclusion = "Závěr"
abstract = "Abstrakt"
keywords = "Klíčová slova"
list-of-symbols = "Seznam použitých zkratek a symbolů"
outline = "Obsah"
acknowledgements = "Poděkování"
intro = "Úvod"

