// created by phatt-23

// Usable themes for white background.
#let usable-themes = (
"ryan-light.tmTheme",
"Coda.tmTheme",
"Dawn.tmTheme",
"Dominion Day.tmTheme",
"Fluidvision.tmTheme",
"Freckle.tmTheme",
"GitHub.tmTheme",
"IR_White.tmTheme",
"Juicy.tmTheme",
"LAZY.tmTheme",
"Mac Classic.tmTheme",
"Notepad2.tmTheme",
"Slush & Poppies.tmTheme",
"Solarized (dark).tmTheme",
"Solarized (light).tmTheme",
"Sweyla674314.tmTheme",
"Tango.tmTheme",
"Tomorrow.tmTheme",
"Whys Poignant.tmTheme",
"close_to_the_sea.tmTheme",
"iPlastic.tmTheme",
"ryan-light.tmTheme",
)

#let fav-themes = (
"Whys Poignant.tmTheme",
"Slush & Poppies.tmTheme",
"Notepad2.tmTheme",
"Mac Classic.tmTheme",
"Juicy.tmTheme",
"IR_White.tmTheme",
"Freckle.tmTheme",
"Fluidvision.tmTheme",
"Dominion Day.tmTheme",
"Dawn.tmTheme",
"Coda.tmTheme",
"ryan-light.tmTheme",
)

#let best-themes = (
"Notepad2.tmTheme", 
"Dawn.tmTheme", 
"ryan-light.tmTheme"
)


#let all-themes = (
"Active4D.tmTheme",
"All Hallow's Eve Custom.tmTheme",
"All Hallow's Eve.tmTheme",
"Amy.tmTheme",
"BBEdit.tmTheme",
"Bespin.tmTheme",
"Birds of Paradise.tmTheme",
"Black Pearl II.tmTheme",
"Black Pearl.tmTheme",
"BlackLight.tmTheme",
"Blackboard Black.tmTheme",
"Blackboard Mod.tmTheme",
"Blackboard New.tmTheme",
"Blackboard.tmTheme",
"Bongzilla.tmTheme",
"Boys & Girls 0.1.tmTheme",
"Brilliance Black.tmTheme",
"Brilliance Dull.tmTheme",
"CSSEdit.tmTheme",
"Claire.tmTheme",
"Classic Modified.tmTheme",
"Clouds Midnight.tmTheme",
"Clouds.tmTheme",
"Coal Graal.tmTheme",
"Cobalt.tmTheme",
"Coda.inkdeep.tmTheme",
"Coda.tmTheme",
"Cool Glow.tmTheme",
"Creeper.tmTheme",
"Daniel Fischer.tmTheme",
"Dawn mod1.tmTheme",
"Dawn.tmTheme",
"Deluxe.tmTheme",
"Django (Smoothy).tmTheme",
"Django Dark.tmTheme",
"Dominion Day.tmTheme",
"Eiffel.tmTheme",
"Emacs Strict.tmTheme",
"Erebus.tmTheme",
"Espresso Libre.tmTheme",
"Espresso Tutti.tmTheme",
"Espresso.tmTheme",
"Fade to Grey.tmTheme",
"Fluidvision.tmTheme",
"ForLaTeX.tmTheme",
"Freckle mod1.tmTheme",
"Freckle mod2.tmTheme",
"Freckle.tmTheme",
"Friendship Bracelet.tmTheme",
"Funky_Dashboard.tmTheme",
"GitHub.tmTheme",
"GlitterBomb.tmTheme",
"Glow.tmTheme",
"Happy happy joy joy 2.tmTheme",
"Heroku.tmTheme",
"HerokuCodeSamples.tmTheme",
"IDLE.tmTheme",
"IR_Black.tmTheme",
"IR_White.tmTheme",
"Juicy.tmTheme",
"LAZY.inkdeep.tmTheme",
"LAZY.tmTheme",
"Lowlight.tmTheme",
"Mac Classic.tmTheme",
"Made of Code.tmTheme",
"MagicWB (Amiga).tmTheme",
"Menage A Trois.tmTheme",
"Merbivore Soft.tmTheme",
"Merbivore.tmTheme",
"Midnight.tmTheme",
"Monokai Dark.tmTheme",
"Monokai Mod (seangaffney).tmTheme",
"Monokai Mod.tmTheme",
"Monokai for Textmaters CUSTOM (philtr).tmTheme",
"Monokai for Textmaters CUSTOM.tmTheme",
"Monokai mod 1.tmTheme",
"Monokai.tmTheme",
"MultiMarkdown.tmTheme",
"Notebook.tmTheme",
"Notepad2.tmTheme",
"Offy.tmTheme",
"Pastels on Dark.tmTheme",
"Pastie.tmTheme",
"Pengwynn menlo.tmTheme",
"Pengwynn.tmTheme",
"Plum Dumb.tmTheme",
"Putty.tmTheme",
"RDark.tmTheme",
"README.md",
"Rails Envy.tmTheme",
"Railscasts - boost.tmTheme",
"Railscasts.tmTheme",
"Resesif.tmTheme",
"Ruby Blue.tmTheme",
"RubyRobot.tmTheme",
"SidewalkChalk.tmTheme",
"SidewalkChalkGreenMod.tmTheme",
"Slush & Poppies.tmTheme",
"Smoothy.tmTheme",
"Solarized (dark).tmTheme",
"Solarized (light).tmTheme",
"SpaceCadet.tmTheme",
"Spectacular.tmTheme",
"Starlight.tmTheme",
"Succulent_1.tmTheme",
"Summer Camp Daybreak.tmTheme",
"Summer Camp Mod.tmTheme",
"Summer Sun.tmTheme",
"Sunburst.tmTheme",
"Sweyla650478.tmTheme",
"Sweyla674314.tmTheme",
"Swyphs II.tmTheme",
"Tango in Twilight.tmTheme",
"Tango.tmTheme",
"Tek.tmTheme",
"Text Ex Machina (Lighter comments).tmTheme",
"Text Ex Machina.tmTheme",
"Tomorrow Night.tmTheme",
"Tomorrow-Night-Blue.tmTheme",
"Tomorrow-Night-Bright.tmTheme",
"Tomorrow-Night-Eighties.tmTheme",
"Tomorrow-Night.tmTheme",
"Tomorrow.tmTheme",
"Tubster.tmTheme",
"Twilight Bright.tmTheme",
"Twilight REMIX.tmTheme",
"Twilight.tmTheme",
"Upstream Sunburst.tmTheme",
"Upstream Vibrant.tmTheme",
"Venom.tmTheme",
"Vibrant Fin.tmTheme",
"Vibrant Ink chopped'n'screwed.tmTheme",
"Vibrant Ink remix.tmTheme",
"Vibrant Ink.tmTheme",
"Vibrant Tango.tmTheme",
"Vintage Aurora.tmTheme",
"Whys Poignant.tmTheme",
"Zachstronaut Theme 4.1.tmTheme",
"Zenburnesque.tmTheme",
"[ Argonaut ].tmTheme",
"barf.tmTheme",
"choco.tmTheme",
"close_to_the_sea.tmTheme",
"fake.tmTheme",
"happydeluxe.tmTheme",
"iLife 05.tmTheme",
"iLife 06.tmTheme",
"iPlastic.tmTheme",
"idleFingers.tmTheme",
"imathis.tmTheme",
"inkdeep.tmTheme",
"krTheme.tmTheme",
"minimal Theme.tmTheme",
"monoindustrial.tmTheme",
"package-metadata.json",
"ryan-light.tmTheme",
"zenburn.tmTheme",
)
