#let inflected = (
  "rovnice": (
    s: (
      "1": "rovnice",
      "2": "rovnice",
      "3": "rovnici",
      "4": "rovnici",
      "5": "rovnice",
      "6": "rovnici",
      "7": "rovnicí",
    ),
    p: (
      "1": "rovnice",
      "2": "rovnic",
      "3": "rovnicím",
      "4": "rovnice",
      "5": "rovnice",
      "6": "rovnicích",
      "7": "rovnicemi",
    ),
  ),
  "kapitola": (
    s: (
      "1": "kapitola",
      "2": "kapitoly",
      "3": "kapitole",
      "4": "kapitolu",
      "5": "kapitolo",
      "6": "kapitole",
      "7": "kapitolou",
    ),
    p: (
      "1": "kapitoly",
      "2": "kapitol",
      "3": "kapitolám",
      "4": "kapitoly",
      "5": "kapitoly",
      "6": "kapitolách",
      "7": "kapitolami",
    ),
  ),
  "obrázek": (
    s: (
      "1": "obrázek",
      "2": "obrázku",
      "3": "obrázku",
      "4": "obrázek",
      "5": "obrázku",
      "6": "obrázku",
      "7": "obrázkem",
    ),
    p: (
      "1": "obrázky",
      "2": "obrázků",
      "3": "obrázkům",
      "4": "obrázky",
      "5": "obrázky",
      "6": "obrázcích",
      "7": "obrázky",
    ),
  ),
  "výpis": (
    s: (
      "1": "výpis",
      "2": "výpise",
      "3": "výpisu",
      "4": "výpise",
      "5": "výpise",
      "6": "výpisu",
      "7": "výpisem",
    ),
    p: (
      "1": "výpisy",
      "2": "výpisů",
      "3": "výpisům",
      "4": "výpisy",
      "5": "výpisy",
      "6": "výpiech",
      "7": "výpisy",
    ),
  ),
  "algoritmus": (
    s: (
      "1": "algoritmus",
      "2": "algoritmu",
      "3": "algoritmu",
      "4": "algoritmus",
      "5": "algoritme",
      "6": "algoritmu",
      "7": "algoritmem",
    ),
    p: (
      "1": "algoritmy",
      "2": "algoritmů",
      "3": "algoritmům",
      "4": "algoritmy",
      "5": "algoritmy",
      "6": "algoritmech",
      "7": "algoritmy",
    ),
  ),
  "tabulka": (
    s: (
      "1": "tabulka",
      "2": "tabulky",
      "3": "tabulce",
      "4": "tabulku",
      "5": "tabulko",
      "6": "tabulce",
      "7": "tabulkou",
    ),
    p: (
      "1": "tabulky",
      "2": "tabulek",
      "3": "tabulkám",
      "4": "tabulky",
      "5": "tabulky",
      "6": "tabulkách",
      "7": "tabulkami",
    ),
  ),
)
