#let inflected = (
  "equ": (
    sg: (
      nom: "rovnice",
      gen: "rovnice",
      dat: "rovnici",
      acc: "rovnici",
      voc: "rovnice",
      loc: "rovnici",
      ins: "rovnicí",
    ),
    pl: (
      nom: "rovnice",
      gen: "rovnic",
      dat: "rovnicím",
      acc: "rovnice",
      voc: "rovnice",
      loc: "rovnicích",
      ins: "rovnicemi",
    ),
  ),
  "chp": (
    sg: (
      nom: "kapitola",
      gen: "kapitoly",
      dat: "kapitole",
      acc: "kapitolu",
      voc: "kapitolo",
      loc: "kapitole",
      ins: "kapitolou",
    ),
    pl: (
      nom: "kapitoly",
      gen: "kapitol",
      dat: "kapitolám",
      acc: "kapitoly",
      voc: "kapitoly",
      loc: "kapitolách",
      ins: "kapitolami",
    ),
  ),
  "fig": (
    sg: (
      nom: "obrázek",
      gen: "obrázku",
      dat: "obrázku",
      acc: "obrázek",
      voc: "obrázku",
      loc: "obrázku",
      ins: "obrázkem",
    ),
    pl: (
      nom: "obrázky",
      gen: "obrázků",
      dat: "obrázkům",
      acc: "obrázky",
      voc: "obrázky",
      loc: "obrázcích",
      ins: "obrázky",
    ),
  ),
  "lst": (
    sg: (
      nom: "výpis",
      gen: "výpise",
      dat: "výpisu",
      acc: "výpise",
      voc: "výpise",
      loc: "výpisu",
      ins: "výpisem",
    ),
    pl: (
      nom: "výpisy",
      gen: "výpisů",
      dat: "výpisům",
      acc: "výpisy",
      voc: "výpisy",
      loc: "výpiech",
      ins: "výpisy",
    ),
  ),
  "alg": (
    sg: (
      nom: "algoritmus",
      gen: "algoritmu",
      dat: "algoritmu",
      acc: "algoritmus",
      voc: "algoritme",
      loc: "algoritmu",
      ins: "algoritmem",
    ),
    pl: (
      nom: "algoritmy",
      gen: "algoritmů",
      dat: "algoritmům",
      acc: "algoritmy",
      voc: "algoritmy",
      loc: "algoritmech",
      ins: "algoritmy",
    ),
  ),
  "tab": (
    sg: (
      nom: "tabulka",
      gen: "tabulky",
      dat: "tabulce",
      acc: "tabulku",
      voc: "tabulko",
      loc: "tabulce",
      ins: "tabulkou",
    ),
    pl: (
      nom: "tabulky",
      gen: "tabulek",
      dat: "tabulkám",
      acc: "tabulky",
      voc: "tabulky",
      loc: "tabulkách",
      ins: "tabulkami",
    ),
  ),
)
